phrase:
  project_id: f3b899e8917c3a40bd38f7852850fe0b
  push:
    sources:
      - file: ./<locale_name>.json
        params:
          file_format: json
          locale_id: en
          update_translations: true
          autotranslate: true
  pull:
    targets:
      - file: ./<locale_name>.json
        params:
          file_format: json
